name: BombLobbers
version: 1.2.0
description:
author: craycray_coco
main: com.inzernettechnologies.bomblobbers.main

commands:
    bls:
        usage: /<command>
        description: BombLobbers Setup
        permission: bomblobbers.setup
        permission-message: I want to setup BombLobbers too, but not today.

    bl:
        usage: /bl <join|leave|list|buy>
        description: BombLobbers User
        permission: bomblobbers.user
        permission-message: Sorry! You don't have permission for that ;(

    bla:
        usage: /bla <reload>
        description: BombLobbers Admin
        permission: bomblobbers.admin
        permission-message: You want to be an admin, eh? Goodluck :)